#
#
# This is a sample newrelic_plugin.yml file. Please move this file
# to the following location if it is not already there:
#
#     ./config/newrelic_plugin.yml
#
# Where the current directory is the directory where your main program resides and is your current
# directory when you run the main program.
#
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
  # Use any valid redis connection string, such as 'host:port' or 'redis://user:pass@host:port:db' 
  #
  # You can/should have one entry for each specific resque namespace on your redis server.
  #
  # Omitting the namespace will show you ONLY stats/queues where namespace is not specified.
  # It does NOT show you overall stats for the entire redis server.
  #  

agents:
  resque_depth:
    -
      redis: '0.0.0.0:6379'
      namespace:
#    -
#      redis: 'redis://redispass@192.168.0.100:6379
#      namespace: 'resque:myapp_1'
#    - 
#      redis: 'redis://redispass@192.168.0.100:6379
#      namespace: 'resque:myapp_2'
